"""Generate deterministic synthetic Rust parity cases from the Python policy.
No cloud access or real participant data. Normalization is performed by Python;
this verifies the Rust decision stage, not a Rust Unicode normalizer.
"""
from pathlib import Path
import json
import math
import random
import sys
sys.path.insert(0,str(Path(__file__).resolve().parent))
from consensus import decide, normalize

ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'backend/rust-core/tests/python_parity.rs'
def q(value): return json.dumps(value,ensure_ascii=False)
def boolean(value): return 'true' if value else 'false'
def option(value):
    if isinstance(value,bool) or not isinstance(value,(int,float)):return 'None'
    if not math.isfinite(value):return 'Some(f64::NAN)' if math.isnan(value) else 'Some(f64::INFINITY)'
    return f'Some({float(value)!r})'
def variant(s):return ''.join(x.capitalize() for x in s.split('_'))
def base():
    record={'uid':'signer','phrase':{'text':'Please close the window.'},'technicalCheck':{'passed':True,'durationSec':12.7}}
    reviews=[{'reviewId':f'review-{i}','uid':f'r{i}','text':'Please close the window.','status':'pending','quality':'good'} for i in range(5)]
    invites={u:{} for u in ['signer',*[r['uid'] for r in reviews]]}
    return record,reviews,invites,{u:True for u in invites}
cases=[]
for n in range(6):
    r,rs,i,a=base();cases.append((f'review_count_{n}',r,rs[:n],i,a))
for duration in [None,False,True,-1,0,0.49,0.5,0.99,1,29.99,30,31,31.01,float('nan'),float('inf')]:
    r,rs,i,a=base();r['technicalCheck']['durationSec']=duration;cases.append((f'duration_{duration}',r,rs[:3],i,a))
for text in ['PLEASE close the window!','Please do not close the window.','Would you shut the window?','Please close two windows.','', '   ', '!!!','Ｐｌｅａｓｅ close the window.']:
    r,rs,i,a=base();rs[0]['text']=text;cases.append(('meaning_'+repr(text),r,rs[:3],i,a))
for text in ['Straße','École','I don’t feel well','１２ apples','a_b','İstanbul']:
    r,rs,i,a=base();r['phrase']['text']=text
    for review in rs:review['text']=text.upper()
    cases.append(('unicode_adapter_'+text,r,rs[:3],i,a))
rng=random.Random(372)
for n in range(100):
    r,rs,i,a=base();r['technicalCheck']['passed']=rng.choice([True,False]);r['technicalCheck']['durationSec']=rng.choice([0.5,1.9,12.7,30,32,None])
    for uid in i:
        a[uid]=rng.random()>.13
        if rng.random()<.12:i[uid]['testOnly']=True
        if uid!='signer' and rng.random()<.22:i[uid]['samePersonAs']=rng.choice(['signer','r0','r1'])
    for review in rs:
        review['text']=rng.choice(['Please close the window.']*3+['Do not close the window.','Would you shut it?',''])
        review['quality']=rng.choice(['good']*3+['poor',None]);review['status']=rng.choice(['pending']*4+['assigned'])
    rng.shuffle(rs);cases.append((f'mixed_{n}',r,rs[:rng.randrange(6)],i,a))
def generate():
    lines=['// Generated by tools/generate_rust_consensus_fixtures.py; synthetic inputs only.',
           'use signrush_core::consensus::*;','use std::collections::BTreeMap;',
           '#[rustfmt::skip]','#[test] fn python_decision_parity() {']
    for name,r,rs,invites,active in cases:
        d=decide(r,rs,invites,active)
        lines.append('{')
        lines.append('let identities=Identities::from(['+','.join('('+q(uid)+'.into(),Identity{same_person_as:'+('Some('+q(v['samePersonAs'])+'.into())' if v.get('samePersonAs') else 'None')+',test_only:'+boolean(v.get('testOnly'))+',active:'+boolean(active.get(uid))+'})' for uid,v in invites.items())+']);')
        lines.append('let input=Input{signer_uid:'+q(r['uid'])+',normalized_reference:'+q(normalize(r['phrase']['text']))+',technical_passed:'+boolean(r['technicalCheck']['passed'] is True)+',duration_seconds:'+option(r['technicalCheck']['durationSec'])+'};')
        lines.append('let reviews=['+','.join('Review{id:'+q(v['reviewId'])+',uid:'+q(v['uid'])+',pending:'+boolean(v['status']=='pending')+',text_present:'+boolean(v['text'].strip())+',normalized_text:'+q(normalize(v['text']))+',quality_good:'+boolean(v['quality']=='good')+'}' for v in rs)+'];')
        excluded=','.join('('+q(k)+'.into(),Exclusion::'+variant(v)+')' for k,v in d['excludedReviews'].items())
        scores=','.join('('+q(k)+'.into(),'+('Some(1.0)' if v==1 else 'None')+')' for k,v in d['referenceScores'].items())
        lines.append('let expected=Outcome{status:Status::'+variant(d['status'])+',independent_reviews:'+str(d['independentReviews'])+',excluded:BTreeMap::from(['+excluded+']),reference_scores:BTreeMap::from(['+scores+']),review_limit:'+str(d['reviewLimit'])+',reward_review_ids:vec!['+','.join(q(v)+'.into()' for v in d['rewardReviewIds'])+'],signer_points:'+str(d['signerPoints'])+',reviewer_points:'+str(d['reviewerPoints'])+'};')
        lines.append('assert_eq!(decide(&input,&reviews,&identities),expected,"case: {}",'+q(name)+');}')
    lines.append('}')
    OUT.parent.mkdir(exist_ok=True);OUT.write_text('\n'.join(lines)+'\n')
    print(f'Generated {len(cases)} Python-oracle cases in {OUT.relative_to(ROOT)}')

if __name__=='__main__':generate()
