export const avatars=['sprout','orbit','blaze','ripple','nova','comet','peach','pixel'];
export const trophies=[{at:25,name:'First spark',asset:'bronze',image:'assets/trophies/spark.png'},{at:100,name:'On a roll',asset:'silver',image:'assets/trophies/silver-rush.png'},{at:250,name:'Gold standard',asset:'gold',image:'assets/trophies/gold-standard.png'},{at:500,name:'Rush legend',asset:'prism',image:'assets/trophies/rush-legend.png'},{at:1000,name:'Lightning league',image:'assets/trophies/sign-champion.png'},{at:2000,name:'Master decoder',image:'assets/trophies/decode-champion.png'},{at:3500,name:'Crown contender',image:'assets/trophies/gold-standard.png'},{at:5000,name:'Rush royalty',image:'assets/trophies/rush-legend.png'}];
export function level(points){const n=Number.isSafeInteger(points)&&points>=0?points:0;return {number:Math.floor(n/25)+1,earned:trophies.filter(t=>n>=t.at),next:trophies.find(t=>n<t.at)};}
export function validProfile(alias,avatar,listed){alias=alias.trim();if(!/^[A-Za-z][A-Za-z0-9 _-]{2,19}$/.test(alias))throw Error('Choose a player name with 3–20 letters, numbers, spaces, _ or -. Start with a letter.');if(!avatars.includes(avatar))throw Error('Choose an avatar.');return {alias,avatar,listed:Boolean(listed)};}
const picture=(avatar,cls='')=>{const img=document.createElement('img');img.src=`assets/avatars/${avatars.includes(avatar)?avatar:'sprout'}.svg`;img.alt='';img.className=cls;return img;};
export class Game {
 constructor(root){this.root=root;this.el=id=>root.querySelector('#'+id);this.epoch=0;this.stops=[];
  for(const id of ['edit-player','board-join'])this.el(id).onclick=()=>this.edit();
  this.el('close-player').onclick=()=>this.el('player-dialog').close();
  this.el('player-form').onsubmit=e=>{e.preventDefault();this.save();};
  this.el('dismiss-celebration').onclick=()=>this.el('celebration').hidden=true;
  this.el('player-retry').onclick=()=>this.connect(this.service);
  for(const a of avatars){const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',a+' avatar');b.dataset.avatar=a;b.append(picture(a));b.onclick=()=>{this.selected=a;this.selection();};this.el('avatar-grid').append(b);}
  for(const [id,direction] of [['trophy-prev',-1],['trophy-next-page',1]]){const button=this.el(id);if(button)button.onclick=()=>{const shelf=this.el('trophy-shelf');shelf.scrollBy({left:direction*shelf.clientWidth*.8,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});};}
  this.reset();
 }
 reset(){this.epoch++;this.stops.forEach(s=>s());this.stops=[];clearTimeout(this.timer);this.service=null;this.profile=null;this.points=null;this.selected='sprout';this.busy=false;this.loaded=false;this.el('player-fields').disabled=false;this.el('save-player').textContent='Save my player';this.el('player-dialog').close();this.el('celebration').hidden=true;this.el('player-alias').value='';this.el('player-listed').checked=false;this.el('player-message').textContent='';this.el('player-retry').hidden=true;this.el('edit-player').disabled=true;this.el('board-join').disabled=true;this.el('board-podium').replaceChildren();this.el('board-list').replaceChildren();this.el('board-status').textContent='Loading the arena…';this.el('player-name').textContent='Your next chapter';this.el('player-level').textContent='Choose your player identity';this.el('player-avatar').src='assets/avatars/sprout.svg';this.drawTrophies(0);}
 selection(){for(const b of this.el('avatar-grid').children)b.setAttribute('aria-pressed',String(b.dataset.avatar===this.selected));}
 async connect(service){this.reset();this.service=service;const epoch=this.epoch;
  this.stops.push(service.board(rows=>{if(epoch===this.epoch)this.drawBoard(rows);},()=>{if(epoch===this.epoch)this.el('board-status').textContent='Rankings couldn’t load. Refresh to try again.';}));
  this.stops.push(service.points(points=>{if(epoch!==this.epoch)return;const old=this.points;this.points=points;this.drawTrophies(points);if(old!==null&&points>old)this.celebrate(points-old,level(points).earned.length>level(old).earned.length);if(this.loaded&&this.profile?.listed)service.sync().catch(()=>{});},()=>{if(epoch===this.epoch)this.el('player-level').textContent='Points temporarily unavailable';}));
  try{const profile=await service.load();if(epoch!==this.epoch)return;this.profile=profile;this.loaded=true;this.drawProfile();if(this.profile?.listed)service.sync().catch(()=>{});}
  catch{if(epoch===this.epoch){this.el('player-level').textContent='Profile unavailable · Try again';this.el('player-retry').hidden=false;}}
 }
 drawProfile(){this.el('edit-player').disabled=!this.loaded;this.el('board-join').disabled=!this.loaded;this.el('player-name').textContent=this.profile?.alias||'Make a name for yourself';this.el('player-avatar').src=`assets/avatars/${avatars.includes(this.profile?.avatar)?this.profile.avatar:'sprout'}.svg`;this.el('board-join').textContent=this.profile?.listed?'Edit leaderboard profile':'Join the leaderboard';this.el('edit-player-label').textContent=this.profile?'Edit player':'Choose avatar';this.drawTrophies(this.points??0);}
 edit(){if(!this.loaded||this.busy)return;this.selected=this.profile?.avatar||'sprout';this.selection();this.el('player-alias').value=this.profile?.alias||'';this.el('player-listed').checked=this.profile?.listed||false;this.el('player-message').textContent='';this.el('player-dialog').showModal();}
 async save(){if(this.busy)return;let p;try{p=validProfile(this.el('player-alias').value,this.selected,this.el('player-listed').checked);}catch(e){this.el('player-message').textContent=e.message;return;}const epoch=this.epoch;this.busy=true;this.el('player-fields').disabled=true;this.el('save-player').textContent='Saving…';
  try{await this.service.save(p);if(epoch!==this.epoch)return;this.profile=p;this.drawProfile();this.el('player-dialog').close();}
  catch{if(epoch===this.epoch)this.el('player-message').textContent='Save wasn’t confirmed. Try again.';}
  finally{if(epoch===this.epoch){this.busy=false;this.el('player-fields').disabled=false;this.el('save-player').textContent='Save my player';}}
 }
 drawTrophies(points){const l=level(points);this.el('player-level').textContent=`Level ${l.number} · ${l.earned.length} / ${trophies.length} trophies`;this.el('trophy-next').textContent=l.next?`${Math.max(0,l.next.at-points)} points to ${l.next.name}`:'Rush royalty unlocked. All 8 trophies are yours!';const shelf=this.el('trophy-shelf');shelf.replaceChildren();for(const t of trophies){const item=document.createElement('div');item.className='trophy-item'+(points>=t.at?' unlocked':' locked');const img=document.createElement('img');img.src=t.image||`assets/trophies/${t.asset}.svg`;img.loading='lazy';img.alt='';const title=document.createElement('strong');title.textContent=t.name;const sub=document.createElement('span');sub.textContent=points>=t.at?'✓ Unlocked':`${t.at.toLocaleString('en-US')} pts`;item.append(img,title,sub);shelf.append(item);}}
 celebrate(delta,trophy){this.el('celebration-title').textContent=trophy?'New trophy unlocked!':'You’re on the rise!';this.el('celebration-text').textContent=`+${delta} approved test points. Nice work!`;this.el('celebration').hidden=false;clearTimeout(this.timer);this.timer=setTimeout(()=>this.el('celebration').hidden=true,6500);}
 drawBoard(rows){const podium=this.el('board-podium'),list=this.el('board-list');podium.replaceChildren();list.replaceChildren();this.el('board-status').textContent=rows.length?'Top 50 opted-in players · All-time test points. Scores refresh when players open SignRush.':'The podium is waiting. Pick your avatar and be one of the first to join.';rows.forEach((r,i)=>{const item=document.createElement('div');item.className=i<3?`podium-player place-${i+1}`:'rank-row';const rank=document.createElement('span');rank.className='rank-number';rank.textContent=String(i+1);const name=document.createElement('strong');name.textContent=r.alias;const score=document.createElement('span');score.className='rank-score';score.textContent=`${r.points} pts`;item.append(rank,picture(r.avatar),name,score);(i<3?podium:list).append(item);});}
}
export function gameService(user,db,sdk){const profile=sdk.doc(db,'gameProfiles',user.uid),entry=sdk.doc(db,'leaderboard',user.uid),wallet=sdk.doc(db,'playerRewards',user.uid);
 async function publish(value){return sdk.runTransaction(db,async tx=>{const current=await tx.get(profile);const rewards=await tx.get(wallet);const p=value??(current.exists()?current.data():null);if(!p)return;const safe=validProfile(p.alias,p.avatar,p.listed);if(value)tx.set(profile,{...safe,updatedAt:sdk.serverTimestamp()});if(safe.listed)tx.set(entry,{alias:safe.alias,avatar:safe.avatar,points:rewards.exists()?rewards.data().points:0,updatedAt:sdk.serverTimestamp()});else tx.delete(entry);});}
 return {load:async()=>{const s=await sdk.getDocFromServer(profile);return s.exists()?s.data():null;},save:publish,sync:()=>publish(),
 points:(next,error)=>sdk.onSnapshot(wallet,s=>{const n=s.exists()?s.data().points:0;next(Number.isSafeInteger(n)&&n>=0?n:0);},error),
 board:(next,error)=>sdk.onSnapshot(sdk.query(sdk.collection(db,'leaderboard'),sdk.orderBy('points','desc'),sdk.limit(50)),s=>next(s.docs.map(d=>d.data())),error)};
}
